CC=g++

CFLAGS=-c -Wall -Wshadow -Winit-self -Wredundant-decls -Wcast-align -Wundef -Wfloat-equal -Winline -Wunreachable-code -Wmissing-declarations -Wmissing-include-dirs -Wswitch-enum -Wswitch-default -Weffc++ -Wmain -Wextra -Wall -g -pipe -fexceptions -Wcast-qual -Wconversion -Wctor-dtor-privacy -Wempty-body -Wformat-security -Wformat=2 -Wignored-qualifiers -Wlogical-op -Wno-missing-field-initializers -Wnon-virtual-dtor -Woverloaded-virtual -Wpointer-arith -Wsign-promo -Wstack-usage=8192 -Wstrict-aliasing -Wstrict-null-sentinel -Wtype-limits -Wwrite-strings -Werror=vla -D_DEBUG -D_EJUDGE_CLIENT_SIDE

all: TestFuncs

TestFuncs: main.o mystrings.o debug.o color_print.o
	$(CC) main.o mystrings.o debug.o color_print.o -o TestFuncs

main.o: main.cpp
	$(CC) $(CFLAGS) main.cpp

mystrings.o: mystrings.cpp
	$(CC) $(CFLAGS) mystrings.cpp

debug.o: debug.cpp
	$(CC) $(CFLAGS) debug.cpp

color_print.o: color_print.cpp
	$(CC) $(CFLAGS) color_print.cpp

clean:
	rm -rf *.o TestFuncs
